// <auto-generated />
using System;
using Crystal.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Crystal.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260415084532_StatusTransitions")]
    partial class StatusTransitions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Crystal.Web.Models.ProjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Внутренний проект для сотрудников.",
                            Name = "Internal Portal"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Учебная демонстрация для сдачи.",
                            Name = "Demo Release"
                        });
                });

            modelBuilder.Entity("Crystal.Web.Models.TaskComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TaskItemId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskComments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Главное - не усложнять решение.",
                            CreatedAt = new DateTime(2026, 4, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            TaskItemId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Начала перенос на PostgreSQL.",
                            CreatedAt = new DateTime(2026, 4, 15, 11, 15, 0, 0, DateTimeKind.Utc),
                            TaskItemId = 1,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Crystal.Web.Models.TaskFieldDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FieldType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBase")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TaskFieldDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FieldType = 2,
                            IsBase = true,
                            IsRequired = true,
                            Name = "Estimate"
                        },
                        new
                        {
                            Id = 2,
                            FieldType = 1,
                            IsBase = true,
                            IsRequired = false,
                            Name = "Due Note"
                        },
                        new
                        {
                            Id = 3,
                            FieldType = 1,
                            IsBase = false,
                            IsRequired = false,
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("Crystal.Web.Models.TaskFieldValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TaskFieldDefinitionId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("TaskFieldDefinitionId");

                    b.HasIndex("TaskItemId", "TaskFieldDefinitionId")
                        .IsUnique();

                    b.ToTable("TaskFieldValues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TaskFieldDefinitionId = 1,
                            TaskItemId = 1,
                            Value = "8"
                        },
                        new
                        {
                            Id = 2,
                            TaskFieldDefinitionId = 2,
                            TaskItemId = 1,
                            Value = "Нужно закончить до презентации"
                        },
                        new
                        {
                            Id = 3,
                            TaskFieldDefinitionId = 3,
                            TaskItemId = 2,
                            Value = "Учебная группа"
                        });
                });

            modelBuilder.Entity("Crystal.Web.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectEntityId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskStatusEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int?>("WorkQueueId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProjectEntityId");

                    b.HasIndex("TaskStatusEntityId");

                    b.HasIndex("WorkQueueId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedToId = 2,
                            CreatedById = 1,
                            Deadline = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Создать базовую MVC структуру и подключить PostgreSQL.",
                            Priority = 3,
                            ProjectEntityId = 2,
                            TaskStatusEntityId = 2,
                            Title = "Подготовить структуру проекта",
                            WorkQueueId = 1
                        },
                        new
                        {
                            Id = 2,
                            AssignedToId = 3,
                            CreatedById = 1,
                            Deadline = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Подготовить краткий список проверок для релиза.",
                            Priority = 2,
                            ProjectEntityId = 1,
                            TaskStatusEntityId = 1,
                            Title = "Составить тест-кейсы",
                            WorkQueueId = 2
                        });
                });

            modelBuilder.Entity("Crystal.Web.Models.TaskStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorClass")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TaskStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorClass = "secondary",
                            Name = "New"
                        },
                        new
                        {
                            Id = 2,
                            ColorClass = "primary",
                            Name = "In Progress"
                        },
                        new
                        {
                            Id = 3,
                            ColorClass = "success",
                            Name = "Done"
                        });
                });

            modelBuilder.Entity("Crystal.Web.Models.TaskStatusTransition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FromTaskStatusEntityId")
                        .HasColumnType("integer");

                    b.Property<int>("ToTaskStatusEntityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ToTaskStatusEntityId");

                    b.HasIndex("FromTaskStatusEntityId", "ToTaskStatusEntityId")
                        .IsUnique();

                    b.ToTable("TaskStatusTransitions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FromTaskStatusEntityId = 1,
                            ToTaskStatusEntityId = 2
                        },
                        new
                        {
                            Id = 2,
                            FromTaskStatusEntityId = 2,
                            ToTaskStatusEntityId = 3
                        },
                        new
                        {
                            Id = 3,
                            FromTaskStatusEntityId = 2,
                            ToTaskStatusEntityId = 1
                        });
                });

            modelBuilder.Entity("Crystal.Web.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("WorkQueueId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("WorkQueueId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = "Management",
                            Email = "admin@crystal.local",
                            FirstName = "Admin",
                            IsAdmin = true,
                            LastName = "Crystal",
                            PasswordHash = "AQAAAAIAAYagAAAAEDj3mQJ128BGBpQv0V/yN5worSBLEVzuc/n7sxWJn1sUZ3s4TU7mJxoLggmGgUGoPg==",
                            Position = "Administrator",
                            WorkQueueId = 1
                        },
                        new
                        {
                            Id = 2,
                            Department = "Development",
                            Email = "anna@crystal.local",
                            FirstName = "Anna",
                            IsAdmin = false,
                            LastName = "Smirnova",
                            PasswordHash = "AQAAAAIAAYagAAAAEEatSRNBGiltJnJtfi4nFEjbb7OuVo+yVKR1MRVfAAWb0ITPfvOwAmtwLq6E4jUVNQ==",
                            Position = "Backend Developer",
                            WorkQueueId = 1
                        },
                        new
                        {
                            Id = 3,
                            Department = "QA",
                            Email = "oleg@crystal.local",
                            FirstName = "Oleg",
                            IsAdmin = false,
                            LastName = "Sidorov",
                            PasswordHash = "AQAAAAIAAYagAAAAEHio+0m1WsyHSr9FzksHbFpOmrnZrUnNWuK1uVdV8gv7tySRMfDP2ysS+tBxdKqNDw==",
                            Position = "QA Engineer",
                            WorkQueueId = 2
                        });
                });

            modelBuilder.Entity("Crystal.Web.Models.WorkQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.ToTable("WorkQueues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Разработчики backend.",
                            Name = "Backend Queue"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Команда тестирования.",
                            Name = "QA Queue"
                        });
                });

            modelBuilder.Entity("Crystal.Web.Models.TaskComment", b =>
                {
                    b.HasOne("Crystal.Web.Models.TaskItem", "TaskItem")
                        .WithMany("Comments")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Crystal.Web.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaskItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Crystal.Web.Models.TaskFieldValue", b =>
                {
                    b.HasOne("Crystal.Web.Models.TaskFieldDefinition", "TaskFieldDefinition")
                        .WithMany("Values")
                        .HasForeignKey("TaskFieldDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Crystal.Web.Models.TaskItem", "TaskItem")
                        .WithMany("FieldValues")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskFieldDefinition");

                    b.Navigation("TaskItem");
                });

            modelBuilder.Entity("Crystal.Web.Models.TaskItem", b =>
                {
                    b.HasOne("Crystal.Web.Models.User", "AssignedTo")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Crystal.Web.Models.User", "CreatedBy")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Crystal.Web.Models.ProjectEntity", "ProjectEntity")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Crystal.Web.Models.TaskStatusEntity", "TaskStatusEntity")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskStatusEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Crystal.Web.Models.WorkQueue", "WorkQueue")
                        .WithMany("Tasks")
                        .HasForeignKey("WorkQueueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedTo");

                    b.Navigation("CreatedBy");

                    b.Navigation("ProjectEntity");

                    b.Navigation("TaskStatusEntity");

                    b.Navigation("WorkQueue");
                });

            modelBuilder.Entity("Crystal.Web.Models.TaskStatusTransition", b =>
                {
                    b.HasOne("Crystal.Web.Models.TaskStatusEntity", "FromTaskStatusEntity")
                        .WithMany("AvailableFromTransitions")
                        .HasForeignKey("FromTaskStatusEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Crystal.Web.Models.TaskStatusEntity", "ToTaskStatusEntity")
                        .WithMany("AvailableToTransitions")
                        .HasForeignKey("ToTaskStatusEntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromTaskStatusEntity");

                    b.Navigation("ToTaskStatusEntity");
                });

            modelBuilder.Entity("Crystal.Web.Models.User", b =>
                {
                    b.HasOne("Crystal.Web.Models.WorkQueue", "WorkQueue")
                        .WithMany("Users")
                        .HasForeignKey("WorkQueueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WorkQueue");
                });

            modelBuilder.Entity("Crystal.Web.Models.ProjectEntity", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Crystal.Web.Models.TaskFieldDefinition", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Crystal.Web.Models.TaskItem", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("FieldValues");
                });

            modelBuilder.Entity("Crystal.Web.Models.TaskStatusEntity", b =>
                {
                    b.Navigation("AvailableFromTransitions");

                    b.Navigation("AvailableToTransitions");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Crystal.Web.Models.User", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("Comments");

                    b.Navigation("CreatedTasks");
                });

            modelBuilder.Entity("Crystal.Web.Models.WorkQueue", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
